"""Post AEGIS PR analysis reports as GitHub pull request comments."""

from __future__ import annotations

import os
from typing import Any

from aegis import config
from aegis.core.orchestrator import AegisReport
from aegis.integrations.github_client import GitHubClient, GitHubError, github_configured

MARKER = "<!-- aegis-report -->"

# Demo CIG PRs → live PRs on GITHUB_REPO_OWNER/GITHUB_REPO_NAME
DEFAULT_CIG_TO_GITHUB = {
    482: 1,  # payment refund / gateway
    500: 2,  # auth signing key rotation
}


def _cfg(name: str, default: str | None = None) -> str:
    getter = getattr(config, "get", None)
    if callable(getter):
        val = getter(name, default)
    else:
        val = getattr(config, name, None) or os.getenv(name, default)
    return (val or "").strip()


def parse_pr_map(raw: str | None) -> dict[int, int]:
    mapping: dict[int, int] = {}
    for part in (raw or "").split(","):
        part = part.strip()
        if not part or ":" not in part:
            continue
        left, right = part.split(":", 1)
        try:
            mapping[int(left.strip())] = int(right.strip())
        except ValueError:
            continue
    return mapping


def resolve_github_pr_number(pr_number: int) -> int:
    """Map a CIG PR number onto the live GitHub PR number."""
    mapping = {**DEFAULT_CIG_TO_GITHUB, **parse_pr_map(_cfg("GITHUB_PR_MAP"))}
    return mapping.get(int(pr_number), int(pr_number))


def format_report_markdown(report: AegisReport, *, github_pr_number: int | None = None) -> str:
    """Human-readable markdown suited for a PR conversation comment."""
    alignment = (report.agent_outputs or {}).get("alignment") or report.story_alignment.get(
        "alignment", "—"
    )
    services = report.blast_radius.get("affected_services") or []
    flows = report.deterministic_features.get("affected_flows") or []
    incidents = report.deterministic_features.get("past_incidents") or []
    files = report.blast_radius.get("files") or []
    github_n = github_pr_number or resolve_github_pr_number(report.pr_number or 0)

    verdict = (report.verdict or "UNKNOWN").upper()
    emoji = {"APPROVE": "✅", "REVIEW": "🔍", "REJECT": "🛑"}.get(verdict, "ℹ️")

    lines = [
        MARKER,
        f"## {emoji} Project AEGIS — Release shield",
        "",
        f"**GitHub PR:** #{github_n}  ",
    ]
    if report.pr_number and int(report.pr_number) != int(github_n):
        lines.append(f"**CIG PR:** #{report.pr_number}  ")
    lines.extend(
        [
            f"**Verdict:** `{verdict}`  ",
            f"**Requirement alignment:** `{alignment}`  ",
            f"**Merge confidence:** {report.merge_confidence:.0f}%  ",
            f"**Regression probability:** {report.regression_probability:.0%}",
            "",
            "### Blast radius",
            "",
        ]
    )
    if services:
        lines.append("**Affected services:** " + ", ".join(f"`{s}`" for s in services))
    else:
        lines.append("_No affected services resolved from the CIG._")
    if flows:
        lines.append("")
        lines.append("**Customer flows:** " + ", ".join(flows))
    if incidents:
        lines.append("")
        lines.append("**Past incidents:** " + ", ".join(f"`{i}`" for i in incidents))

    if files:
        lines.extend(["", "### Changed files", ""])
        for f in files:
            path = f.get("path") or "?"
            ms = f.get("microservice") or "—"
            add = f.get("additions") or 0
            dele = f.get("deletions") or 0
            lines.append(f"- `{path}` ({ms}, +{add}/−{dele})")

    tests = report.recommended_tests or []
    lines.extend(["", "### Recommended tests (targeted)", ""])
    if tests:
        for t in tests:
            lines.append(f"- `{t.get('id')}` ({t.get('source', '?')})")
    else:
        lines.append("_No tests recommended._")

    synth = ""
    raw = report.agent_outputs.get("raw") or {}
    if isinstance(raw, dict):
        for key, val in raw.items():
            if "Orchestrator" in str(key) or "orchestrator" in str(key).lower():
                synth = (val or "").strip()
                break
        if not synth:
            for val in raw.values():
                if val and str(val).strip():
                    synth = str(val).strip()[:800]
                    break
    if synth:
        lines.extend(["", "### Agent summary", "", synth[:1200]])

    lines.extend(
        [
            "",
            "---",
            "_Generated by [Project AEGIS](http://localhost:8501) "
            "(Connected Intelligence Graph). "
            "Requires human judgment before merge._",
        ]
    )
    return "\n".join(lines)


def post_report_to_pr(
    report: AegisReport,
    *,
    as_review: bool = False,
    client: GitHubClient | None = None,
) -> dict[str, Any]:
    """Post the report as a PR conversation comment (default) or a PR review COMMENT."""
    if report.pr_number is None:
        raise GitHubError("Report has no pr_number")
    if not github_configured() and client is None:
        raise GitHubError(
            "GitHub not configured. Set GITHUB_TOKEN, GITHUB_REPO_OWNER, GITHUB_REPO_NAME"
        )

    github_n = resolve_github_pr_number(int(report.pr_number))
    body = format_report_markdown(report, github_pr_number=github_n)
    gh = client or GitHubClient()
    if as_review:
        result = gh.create_pull_review_comment_summary(github_n, body)
    else:
        result = gh.create_issue_comment(github_n, body)

    return {
        "ok": True,
        "pr_number": report.pr_number,
        "github_pr_number": github_n,
        "mode": "review" if as_review else "comment",
        "id": result.get("id") if isinstance(result, dict) else None,
        "html_url": result.get("html_url") if isinstance(result, dict) else None,
        "repo": f"{gh.owner}/{gh.repo}",
    }


def maybe_post_report(report: AegisReport) -> dict[str, Any]:
    """Auto-post after analysis. Never raises — callers keep showing the report."""
    if not github_configured():
        return {
            "ok": False,
            "skipped": True,
            "error": "GitHub MCP not configured",
        }
    try:
        return post_report_to_pr(report, as_review=False)
    except GitHubError as exc:
        return {
            "ok": False,
            "skipped": False,
            "error": str(exc),
            "body": exc.body,
            "pr_number": report.pr_number,
            "github_pr_number": resolve_github_pr_number(report.pr_number or 0),
        }
    except Exception as exc:
        return {
            "ok": False,
            "skipped": False,
            "error": str(exc),
            "pr_number": report.pr_number,
        }
